// import type * as DocsPlugin from '@docusaurus/plugin-content-docs';

// export default {
  
//     // default https://docusaurus.io/docs/sidebar/autogenerated sidebar slice based on hierarchy under docs/
//     refarchSidebar: [ { type: 'category', label: 'Reference Architecture', items: [
//       {
//         type: 'doc',
//         id: 'ref-arch/RA0000/id-ra0000'
//       },
//       {
//         type: 'doc',
//         id: 'ref-arch/RA0001/id-ra0001'
//       },
//       {
//         type: 'doc',
//         id : 'ref-arch/RA0002/id-ra0002'
//       }
//     ] } ],
   
//     // custom auto-generated sidebar slices - see src/_scripts/_sidebarGenerator.js
//     // dirname is used for matching/filtering documents based on tags
//     exploreallrefarch: [{ type: "autogenerated", dirName: 'exploreallrefarch' }],
//     azure: [ { type: 'autogenerated', dirName: 'azure' } ],
//     aws: [ { type: 'autogenerated', dirName: 'aws' } ],
//     gcp: [ { type: 'autogenerated', dirName: 'gcp' } ],
//     appdev: [ { type: 'autogenerated', dirName: 'appdev' } ],
//     ai: [ { type: 'autogenerated', dirName: 'ai' } ],
//     data: [ { type: 'autogenerated', dirName: 'data' } ],
//     integration: [ { type: 'autogenerated', dirName: 'integration' } ],
//     opsec: [ { type: 'autogenerated', dirName: 'opsec' } ]
  
//   } satisfies DocsPlugin.SidebarsConfig;


import type * as DocsPlugin from '@docusaurus/plugin-content-docs';

// 1. ADD this import statement at the top.
// It loads the file generated by our script.
// Assuming this file and the generated file are both in the project root.
import refArchGenerated from './sidebars-refarch-generated.js';


const sidebars: DocsPlugin.SidebarsConfig = {
  
    // 2. ADD the spread operator here.
    // This merges the contents of the imported file (which contains 'refarchSidebar')
    // into this main configuration object.
    // ...refArchGenerated,
    // ...refArchGenerated,
  refarchSidebar: [ { type: 'autogenerated', dirName: '.' } ],
    // 3. REMOVE the entire manual 'refarchSidebar' section that was here.
   
    // All of your other sidebars remain unchanged.
    exploreallrefarch: [{ type: "autogenerated", dirName: 'exploreallrefarch' }],
    azure: [ { type: 'autogenerated', dirName: 'azure' } ],
    aws: [ { type: 'autogenerated', dirName: 'aws' } ],
    gcp: [ { type: 'autogenerated', dirName: 'gcp' } ],
    appdev: [ { type: 'autogenerated', dirName: 'appdev' } ],
    ai: [ { type: 'autogenerated', dirName: 'ai' } ],
    data: [ { type: 'autogenerated', dirName: 'data' } ],
    integration: [ { type: 'autogenerated', dirName: 'integration' } ],
    opsec: [ { type: 'autogenerated', dirName: 'opsec' } ]
  
  };

export default sidebars;