import type * as DocsPlugin from '@docusaurus/plugin-content-docs';

export default {
    // default https://docusaurus.io/docs/sidebar/autogenerated sidebar slice based on hierarchy under docs/
    refarchSidebar: [{ type: 'autogenerated', dirName: '.' }],

} satisfies DocsPlugin.SidebarsConfig;
