
# Create a new document from scratch
POST http://localhost:4004/quickstart/document-service/createNewDocument HTTP/1.1
Content-Type: application/json
Authorization: Basic alice:

{
  "title": "Business Data Cloud - The Data Foundation for Agentic AI",
  "description": "This reference architecture is about Business Data Cloud, the data foundation for agentic AI.",
  "parentId": null,
  "tags": ["genai", "agents", "data"],
  "contributorsUsernames": ["alice", "bob", "fred"],
  "editorState": "{\"state\":{\"someProperty\":\"property value\"}}"
}

###

# Replace the full contributor set of one document
POST http://localhost:4004/quickstart/document-service/setDocumentContributors HTTP/1.1
Content-Type: application/json
Authorization: Basic alice:

{
  "documentId": "657E1690-0A34-4882-BEDC-25CEA8641BA2",
  "contributorsUsernames": ["bob"]
}

###

# Replace the full tag set of one document
POST http://localhost:4004/quickstart/document-service/setDocumentTags HTTP/1.1
Content-Type: application/json
Authorization: Basic alice:

{
  "documentId": "657E1690-0A34-4882-BEDC-25CEA8641BA2",
  "tags": ["agents", "data"]
}