name: Build for GitHub Pages

permissions: {}

on:
    push:
        branches:
            - main
            - dev
jobs:
    build:
        name: Build Site
        runs-on: ubuntu-latest
        timeout-minutes: 30
        permissions:
            contents: read
            pages: write
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
              with:
                  node-version: '24'
                  cache: npm

            - name: Install dependencies
              run: npm ci
            - name: Build website
              run: npm run build

            - name: Upload Build Artifact
              uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
              with:
                  path: build
