name: Deploy to GitHub Pages

on:
    workflow_dispatch:

jobs:
    build:
        name: Build Docusaurus
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: latest
                  cache: npm

            - name: Install dependencies
              run: npm ci
            - name: Fetch contributors details from GitHub API
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              run: node src/_scripts/_fetch-contributors-details.js
            - name: Export drawios to svgs
              run: DOCKER=1 node src/_scripts/_export-drawios.js
            - name: Build website
              run: npm run build

            - name: Upload Build Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: build

    deploy:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        needs: build

        permissions:
            contents: write
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Download Build Artifact
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: build

            - name: Ensure site branch exists
              run: |
                  git fetch origin site || git checkout -b site
                  git checkout site

            - name: Deploy to GitHub Pages
              run: |
                  git config user.email "actions-bot@github.com"
                  git config user.name "github-actions[bot]"

                  cp -r build/* .
                  git add --all

                  if ! git diff --cached --quiet; then
                    git commit -m "Deploy to GitHub Pages"
                    git push origin site --force
                  else
                    echo "No changes to deploy"
                  fi
