name: Release V2 Site Build

on:
  workflow_dispatch:

env:
  PREVIEW_FOLDER: preview/releasev2

jobs:
  build:
    name: Build Site for Release V2 preview
    runs-on: ubuntu-latest
    env:
      VALIDATOR_API_URL: ${{ secrets.VALIDATOR_API_URL }}
      BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
      EXPRESS_BACKEND_URL: ${{ secrets.EXPRESS_BACKEND_URL }}
    steps:
      - name: Checkout Release V2 Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Get pages deployment URL
        run: |
          pages_url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
          url=$(echo $pages_url|cut -d'/' -f 1)//$(echo $pages_url|cut -d'/' -f 3)
          base_url=$(echo $pages_url|cut -d'/' -f 4)
          echo "url=$url" >> "$GITHUB_ENV"
          echo "base_url=$base_url" >> "$GITHUB_ENV"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Patch docusaurus.config.ts for Release V2 preview
        run: |
          sed -E -i "s^url:(..*)^url: '${{ env.url }}',^g" docusaurus.config.ts
          sed -E -i "s^const baseUrl = '(.*)';^const baseUrl = '/@${{ env.PREVIEW_FOLDER }}/';^g" docusaurus.config.ts
          sed -E -i "s^title: 'Build resilient apps with SAP BTP',^title: 'Build resilient apps with SAP BTP (Release V2 Preview)',^g" docusaurus.config.ts
          sed -E -i "s^title: 'Architecture Center'^title: 'Architecture Center (Release V2 Preview)'^g" docusaurus.config.ts
          sed -E -i "s^logo: \{^logo: \{href: 'https://github.com/${{ github.repository }}/tree/release-v2',^g" docusaurus.config.ts

      - name: Verify Patch Application
        run: cat docusaurus.config.ts

      - name: Fetch contributors details from GitHub API
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: node src/_scripts/_fetch-contributors-details.js

      - name: Export drawios to svgs
        run: DOCKER=1 node src/_scripts/_export-drawios.js

      - name: Build Website
        run: npm run build

      - name: Delete sitemap.xml
        run: |
          if [ -f build/sitemap.xml ]; then
            rm build/sitemap.xml
            echo "Deleted sitemap.xml from build output."
          else
            echo "No sitemap.xml found to delete."
          fi

      - name: Delete robots.txt
        run: |
          if [ -f build/robots.txt ]; then
            rm build/robots.txt
            echo "Deleted robots.txt from build output."
          else
            echo "No robots.txt found to delete."
          fi

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy Site for Release V2 Preview
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAASAPCOM_PAT }}

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          path: build/

      - name: Set up Git
        run: |
          git config --global user.email "paa@sap.com"
          git config --global user.name "paasapcom"

      - name: Switch to Pages Branch
        run: |
          gh_pages_branch=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.source.branch')
          git fetch origin $gh_pages_branch
          git checkout $gh_pages_branch
          echo "gh_pages_branch=$gh_pages_branch" >> "$GITHUB_ENV"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Drop Previous Content
        run: |
          rm -rf @${{ env.PREVIEW_FOLDER }}
          mkdir -p @${{ env.PREVIEW_FOLDER }}

      - name: Extract Build Content
        run: |
          if [[ -d "build" && "$(ls -A build)" ]]; then
            mv build/* @${{ env.PREVIEW_FOLDER }}/
            cd @${{ env.PREVIEW_FOLDER }}/
            tar -xvf github-pages/artifact.tar
            rm github-pages/artifact.tar
          else
            echo "No build files found. Skipping move step."
          fi

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAASAPCOM_PAT }}
        run: |
          git add -A
          if [[ "$(git status -s)" ]]; then
            git commit -m "site build ➝ gh pages [skip ci]"
            git push -f origin ${{ env.gh_pages_branch }}
          fi

  notify:
    name: Notify Deployment Complete
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for deployment
        run: sleep 120s

      - name: Output Preview Link
        run: |
          echo "🚀 Release V2 preview site has been deployed!"
          echo "📍 Preview URL: https://architecture.learning.sap.com/@${{ env.PREVIEW_FOLDER }}"
          echo "🔗 Direct link: https://architecture.learning.sap.com/@${{ env.PREVIEW_FOLDER }}/"
