name: Spell Check

on:
    workflow_dispatch:

jobs:
    spell-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout base repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Run spell check (only specific folders)
              uses: check-spelling/check-spelling@v0.0.20
              with:
                  paths: |
                      docs/
                      community/
                      guidance/

            - name: Upload spelling artifacts
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: spelling-artifacts
                  path: .github/actions/spelling/
